name: "Terraform CI/CD"

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  ARM_USE_OIDC: true
  ARM_CLIENT_ID: "8a7fb27a-fe8d-4120-b11a-ebb0154ca82e"
  ARM_SUBSCRIPTION_ID: "5eb83737-e0c8-46c1-818d-4d9725820e3f"
  ARM_TENANT_ID: "e39de75c-b796-4bdd-888d-f3d21250910c"
  ARM_ACCESS_KEY: "${{ secrets.ARM_ACCESS_KEY }}"
  ARM_CLIENT_SECRET: "${{ secrets.ARM_CLIENT_SECRET }}"

defaults:
  run:
    shell: bash
    working-directory: ./infra/tf-app

jobs:
  drift:
    name: Drift Detection
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./infra/tf-app

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.5"

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: "8a7fb27a-fe8d-4120-b11a-ebb0154ca82e"
          tenant-id: "e39de75c-b796-4bdd-888d-f3d21250910c"
          subscription-id: "5eb83737-e0c8-46c1-818d-4d9725820e3f"
          enable-AzPSSession: false
          audience: api://AzureADTokenExchange

      - name: Terraform Init
        run: terraform init

      - name: Check for Drift
        id: drift
        run: |
          terraform plan -detailed-exitcode \
            -var="client_id=$ARM_CLIENT_ID" \
            -var="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" \
            -var="subscription_id=$ARM_SUBSCRIPTION_ID" \
            -var="tenant_id=$ARM_TENANT_ID" \
            -no-color || export exitcode=$?

          if [ $exitcode -eq 2 ]; then
            echo "::warning::Infrastructure drift detected!"
            echo "drift_detected=true" >> $GITHUB_OUTPUT
          else
            echo "No drift detected"
            echo "drift_detected=false" >> $GITHUB_OUTPUT
          fi

  tflint:
    name: TFLint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./infra/tf-app

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.50.0

      - name: Initialize TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact

  static:
    name: Static Analysis
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./infra/tf-app

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.5"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

  plan:
    runs-on: ubuntu-latest
    name: Terraform Plan
    environment:
      name: production
      url: ${{ github.server_url }}/${{ github.repository }}/deployments
    defaults:
      run:
        shell: bash
        working-directory: ./infra/tf-app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: "8a7fb27a-fe8d-4120-b11a-ebb0154ca82e"
          tenant-id: "e39de75c-b796-4bdd-888d-f3d21250910c"
          subscription-id: "5eb83737-e0c8-46c1-818d-4d9725820e3f"
          enable-AzPSSession: false
          audience: api://AzureADTokenExchange

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        id: tf-plan
        run: |
          terraform plan \
            -var="client_id=$ARM_CLIENT_ID" \
            -var="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" \
            -var="subscription_id=$ARM_SUBSCRIPTION_ID" \
            -var="tenant_id=$ARM_TENANT_ID" \
            -input=false -no-color | tee plan_output.txt

      - name: Create String Output
        id: tf-plan-string
        run: |
          delimiter="$(openssl rand -hex 8)"
          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
          echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo '```terraform' >> $GITHUB_OUTPUT
          cat plan_output.txt >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo "</details>" >> $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT

      - name: Publish Terraform Plan to Task Summary
        env:
          SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
        run: |
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

      - name: Push Terraform Output to PR
        if: github.ref != 'refs/heads/main'
        uses: actions/github-script@v7
        env:
          SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `${process.env.SUMMARY}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

  apply:
    needs: [plan, static, tflint, drift]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Terraform Apply
    environment:
      name: production
      url: ${{ github.server_url }}/${{ github.repository }}/deployments

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: "8a7fb27a-fe8d-4120-b11a-ebb0154ca82e"
          tenant-id: "e39de75c-b796-4bdd-888d-f3d21250910c"
          subscription-id: "5eb83737-e0c8-46c1-818d-4d9725820e3f"
          enable-AzPSSession: false
          audience: api://AzureADTokenExchange

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan and Apply
        run: |
          terraform plan \
            -var="client_id=$ARM_CLIENT_ID" \
            -var="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" \
            -var="subscription_id=$ARM_SUBSCRIPTION_ID" \
            -var="tenant_id=$ARM_TENANT_ID" \
            -input=false -out=tfplan

          terraform apply -auto-approve tfplan
