name: "Terraform Static Analysis"

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/tf-app/**'
      - '.github/workflows/infra-static-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'infra/tf-app/**'
      - '.github/workflows/infra-static-tests.yml'

permissions:
  contents: read
  pull-requests: read

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra/tf-app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.50.0

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact

      - name: Terraform Init
        id: init
        run: terraform init -backend=false

      - name: Terraform Validate
        id: validate
        run: terraform validate
